.PHONY: clean All

All:
	@echo "----------Building project:[ serial_implementation - Debug ]----------"
	@cd "serial_implementation" && "$(MAKE)" -f  "serial_implementation.mk"
clean:
	@echo "----------Cleaning project:[ serial_implementation - Debug ]----------"
	@cd "serial_implementation" && "$(MAKE)" -f  "serial_implementation.mk" clean
